### PR TITLE
Payment channel example

### PR DESCRIPTION
**Pull request by leandro-ro**
This new example presents the basic (payment channel) functionality of go-perun. It is replacing the "simple client".

### CODE REVIEW

**Comment by leandro-ro** [comment]
Please have a look @matthiasgeihs .
The PR includes all the payment channel code of #6 

I removed the TODOs and switched from Wei to Eth. Please check this part in your last review.

**Comment by matthiasgeihs** [comment]
@leandro-ro 

I have made a small revision and also adapted the CI.

We might still consider to wait with merging until the new go-perun version, 0.9.0, is realeased. In the meantime, you can already start working on the text for app channels. Alternatively, we can merge with 0.8.0 and update later.

**Comment by leandro-ro** [comment]
Thanks @matthiasgeihs 
Let's wait for 0.9.0 then to fix the idx stuff.

**Comment by matthiasgeihs** [comment]
I fixed the CI and re-introduced the `simple-client`, which we can remove after we updated the tutorial.

We can merge with go-perun 0.8.0.

**Review by matthiasgeihs — APPROVED** [review]

**Pull request merged**
